### ISSUE TITLE
Repository restructuring -- combining with PrestoGP_Pesticides

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/PrestoGP#14]
This repository is structured for a R package. I think the existing [PrestoGP_Pesticide](https://github.com/Spatiotemporal-Exposures-and-Toxicology/PrestoGP_Pesticides) repository needs to be integrated into a part of this repository for both the ease of maintenance and the integration of an effective demonstration of the functions of PrestoGP. After a discussion with Kyle, we suggest taking this directory structure:

#### PrestoGP
- Standard R package components: included in the package build and submission to CRAN
    - `./R`: R functions
    - `./data`: a small subset of pesticide analysis data (e.g., data in NC), possibly in addition to the current US_ST_NO2_Data in PrestoGP package.
    - `./man`: *.Rd files, generated from roxygen2
    - `./src`: C++ source codes and `Makevars`.
    - `./tests`: `testthat` tests, which are executable for GitHub Action test-coverage workflow
    - `./vignettes`: demonstration R markdown files for PrestoGP model classes (`SpatialModel`, `SpatioTemporalModel`, `MultivariateVecchiaModel`, etc.) using files in `./data`
- For manuscript/paper
    - `./Pesticide_Analysis`: analysis codes for pesticide modeling
        - `./Pesticide_Analysis/code`: similar to `code` folder in PrestoGP_Pesticides repository; R, rmd, qmd files are organized as follows
            - `./Pesticide_Analysis/code/00_Load_Packages`
            - `./Pesticide_Analysis/code/01_Create_Dataset`
            - `./Pesticide_Analysis/code/02_Geographic_Covariates`
            - `./Pesticide_Analysis/code/03_Model_Fitting_and_Prediction`
        - `./Pesticide_Analysis/input`: shareable input data. Potentially pointing to the external websites and repository
        - `./Pesticide_Analysis/output`: thematic/cleaned covariates and outcomes for model fitting and prediction

#### TODO
- Insang: make a new branch for implementing the directory structure

**Comment by kyle-messier** [comment]
new `targets` pipeline
