### ISSUE TITLE
estimate_betas should allow alternative penalties

### ISSUE THREAD

**Issue by ericbair-sciome** [NIEHS/PrestoGP#29]
Currently estimate_betas uses an L1 lasso penalty based on glmnet. We should allow alternative penalties such as ridge regression or SCAD.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
combine with issue #24 @ericbair-sciome  @sciome-bot

**Comment by ericbair-sciome** [comment]
Issue 24 is slightly different because we want to investigate it and possibly make the relaxed lasso the default if it outperforms the regular lasso. For this issue, we just want to give users the option, and that doesn't require any experimentation.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
ok, I moved #24 up the backlog then.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@ericbair-sciome @sciome-bot @sigmafelix  

You can link an issue with hash-tag-followed-by-the-number. Kind of like using @ to tag a person. e.g. #24

**Comment by kyle-messier** [comment]
closing - issue #24 covers this
