### ISSUE TITLE
Soil survey -- covariate calculation

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/PrestoGP#3]
- Target: [Gridded National Soil Survey Geographic Database (gNATSGO)](https://www.nrcs.usda.gov/resources/data-and-reports/gridded-national-soil-survey-geographic-database-gnatsgo)
- File footprint: 8.5 GB compressed (75 GB uncompressed)
- Computation strategy: using file proxy instead of reading the entire raster into memory

**Comment by kyle-messier** [comment]
We are using `openlandmap` soil data
