### ISSUE TITLE
Correlation distance

### ISSUE THREAD

**Issue by ericbair-sciome** [NIEHS/PrestoGP#35]
Check and potentially implement a correlation-based distance. The distance metric may be better for calculating neighbors across space, time, and outcomes. Use the correlation distance outlined in MJ & Katzfuss. They have simple code that should be portable and require little changes to the current code.

**Comment by ericbair-sciome** [comment]
I think @brian-bk22 told me that he has done this and found that it was much slower and didn't meaningfully change the results. So I don't think it is a super high priority to get this into the package. I know @brian-bk22 is slammed with a couple other projects right now, but I decided to go ahead and put this on the issue tracker so we don't forget about it. One of us will work on adding this when we have some extra time.

**Comment by kyle-messier** [comment]
@ericbair-sciome @brian-bk22 We've gone other directions, so I'm closing this for now
