### ISSUE TITLE
update README with critical functionality

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/PrestoGP#55]
The readme needs to be updated to provide critical installation and use instructions. 

1. Installation (via github and template for CRAN) 
2. Description of key capabilities: (a) single outcome, full PrestoGP, (b) multivariate outcome, full PrestoGP, (c) single outcome Vecchia PrestoGP, (d) multivariate outcome Vecchia PrestoGP, (e) including censored outcomes in each 
3. Model Fitting functions
4. Prediction at unobserved location functions

**Comment by ericbair-sciome** [comment]
I added all of this to the latest release.
