### ISSUE TITLE
LOD imputation is very slow when the number of missing observations is large

### ISSUE THREAD

**Issue by ericbair-sciome** [NIEHS/PrestoGP#69]
I'm worried that it will be prohibitively slow on the pesticide data. We have some ideas on how to speed it up, but some more work and testing is needed.

**Comment by ericbair-sciome** [comment]
This is fixed in the latest update. I used the nearest neighbor covariance idea using the paper you sent me, and that increased the speed significantly. For some reason it won't let me link the pull request that was just created, but I will close this whenever the latest pull request is accepted.

**Comment by kyle-messier** [comment]
@ericbair-sciome This is great news!

**Comment by ericbair-sciome** [comment]
I'm closing this since it is fixed with the latest update.
