### ISSUE TITLE
'MultivariateVecchiaModel' output returns and print

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/PrestoGP#76]
### `MultivariateVecchiaModel` model return suggestions 

- [ ] imputed values - update documentation in `PrestoGPModel-class` to reflect that this includes imputed values
- [ ] Full linear model (glmnet) model path - would like to create the classic beta path plot
- [ ] We need to figure out the appropriate validation metric to calculate and return 
- [ ] Description/Explanation for Wald and other prediction stats

### `MultivariateVecchiaModel` model print/show suggestions 

- [ ] Exclude zero betas
- [ ] Pretty `gt` table output
- [ ] Method for glmnet model path 
- [ ] For `predict` method, Show output by outcome (a list or table). Currently multivariate input is a list, but predict output is a vector.

**Comment by ericbair-sciome** [comment]
Most of the items listed above are resolved in 0.2.0.9038. The only outstanding items are the validation metric and gt table output. I am inclined to close this for now. We already have an issue for validation (#77), and I don't think there is a simple solution. And "pretty" table output is tricky given that the number of coefficients varies across outcomes. I suppose we could create a prettier version of the theta's (excluding the correlations), but I'm not sure how I would format output tables other than that. I'm open to suggestions.

**Comment by kyle-messier** [comment]
@ericbair-sciome I'd say once the most recent PR passes the tests, then you can close this out.

**Comment by ericbair-sciome** [comment]
I'm closing this based on your earlier comment.
